finish hw-2
GlieXik/nodejs-homeworks pull request #1
Opened 2022-10-29 06:44 UTC by GlieXik

2022-10-29 13:13 UTC, Eastvarga commented on models/contacts.js
> +  db[idx] = { id: nanoid(), ...body };
Чому при апдейті елемента Ви вирішили змінити його id? це критичне зауваження - не треба цього робити. Id це унікальний ідентифікатор нашого елементу він ніколи не змінюється після його створення.
Також зауваження в цьому коді є мутація масиву. Змінна db в цій частині репрезентує старі данні в базі. Краще використати  методи масиву (наприклад map()) для створення нового масиву з оновленими даними та його записати в файл

2022-10-29 13:17 UTC, Eastvarga commented on routes/api/contacts.js
> +    .json({ status: "success", message: { contacts: contactsDB } });
Будьте уважними при ознайомленні з ДЗ
для успішної відповіді структура відповіді повинна бути json( contactsDB), і так по всім раутам

2022-10-29 13:17 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.status(200).json({ status: "success", message: { contact: data } });
теж саме

2022-10-29 13:21 UTC, Eastvarga requested changes
Є зауваження до виконання ДЗ.
Їх треба усунути.

2022-10-30 11:03 UTC, GlieXik commented on models/contacts.js
> +  db[idx] = { id: nanoid(), ...body };
fixed

2022-10-30 11:08 UTC, GlieXik commented on routes/api/contacts.js
> +    .json({ status: "success", message: { contacts: contactsDB } });
fixed

2022-10-30 11:53 UTC, Eastvarga commented on models/contacts.js
> +  Object.assign(oldContact, body);
Гарне рішення, але так не роблять. Коли в коді багато мутацій дуже погано орієнтуватись в такому коді. Спробуйте знайти рішення без мутацій елементу масиву в такий спосіб надалі

2022-10-30 11:57 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.status(200).json({ message: "contact update" });
Тут краще також повертати оновлений елемент.
Неуважність це дуже погано. Уявіть що ТЗ сформувам замовник, та бачить невідповідність, що він подумає, як гадаєте? А замовник платить кошти за виконану роботу.
"По результату работы функции возвращает обновленный объект контакта и статусом 200."

2022-10-30 11:59 UTC, Eastvarga approved these changes
ДЗ прийнято, критичних зауважень немає.
Але зверніть увагу на мої коментарі

2022-10-30 12:00 UTC, merged

2022-10-30 12:11 UTC, GlieXik commented on models/contacts.js
> +  Object.assign(oldContact, body);
Мені здається що Obj.assing не мутує код, чи я не правильно його використав?

2022-10-30 15:34 UTC, Eastvarga commented on models/contacts.js
> +  Object.assign(oldContact, body);
oldContact це змінна типу посилання, Object.assign(oldContact, body) ви змінюєте данні об'єкта на котрий посилається oldContact от же, Ви фактично змінюєте данні елемента в масиві - мутуєте масив. В рамках поточної логіки це не суттєво та не критично, однак це може призвести до спокуси використання токого підходу і там де це зовсім не потрібно, та ускладнить читання коду.